name: Publish RN package (manual)

on:
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install deps
        working-directory: packages/sparkfx-rn
        run: npm install

      - name: Verify npm auth
        run: npm whoami

      - name: Build
        working-directory: packages/sparkfx-rn
        run: npm run build

      - name: Test (non-blocking for initial release)
        working-directory: packages/sparkfx-rn
        run: npm test --silent || echo "No tests or failures ignored for initial release"

      - name: Publish
        working-directory: packages/sparkfx-rn
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
